# Generated by Django 4.0.4 on 2022-07-05 09:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('subject', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='avatar.png', null=True, upload_to='image')),
                ('Gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Transgender', 'T')], max_length=15, null=True)),
                ('Profession', models.CharField(choices=[('accountant', 'accountant'), ('actor', 'actor'), ('actress', 'actress'), ('air traffic controller', 'air traffic controller'), ('architect', 'architect'), ('artist', 'artist'), ('attorney', 'attorney'), ('banker', 'banker'), ('bartender', 'bartender'), ('barber', 'barber'), ('Blogger', 'Blogger'), ('bookkeeper', 'bookkeeper'), ('builder', 'builder'), ('businesswoman', 'businesswoman'), ('businessperson', 'businessperson'), ('butcher', 'butcher'), ('carpenter', 'carpenter'), ('cashier', 'cashier'), ('chef', 'chef'), ('coach', 'coach'), ('dental hygienist', 'dental hygienist'), ('dentist', 'dentist'), ('designer', 'designer'), ('developer', 'developer'), ('dietician', 'dietician'), ('doctor', 'doctor'), ('economist', 'economist'), ('editor', 'editor'), ('electrician', 'electrician'), ('engineer', 'engineer'), ('farmer', 'farmer'), ('filmmaker', 'filmmaker'), ('fisherman', 'fisherman'), ('flight attendant', 'flight attendant'), ('jeweler', 'jeweler'), ('judge', 'judge'), ('lawyer', 'lawyer'), ('mechanic', 'mechanic'), ('musician', 'musician'), ('nutritionist', 'nutritionist'), ('nurse', 'nurse'), ('optician', 'optician'), ('painter', 'painter'), ('pharmacist', 'pharmacist'), ('photographer', 'photographer'), ('physician', 'physician'), ("physician's assistant", "physician's assistant"), ('pilot', 'pilot'), ('plumber', 'plumber'), ('police officer', 'police officer'), ('politician', 'politician'), ('professor', 'professor'), ('programmer', 'programmer'), ('psychologist', 'psychologist'), ('receptionist', 'receptionist'), ('salesman', 'salesman'), ('salesperson', 'salesperson'), ('saleswoman', 'saleswoman'), ('secretary', 'secretary'), ('singer', 'singer'), ('surgeon', 'surgeon'), ('teacher', 'teacher'), ('therapist', 'therapist'), ('translator', 'translator'), ('undertaker', 'undertaker'), ('veterinarian', 'veterinarian'), ('videographer', 'videographer'), ('waiter', 'waiter'), ('waitress', 'waitress'), ('writer', 'writer'), ('others', 'others')], default='Blogger', max_length=50)),
                ('phone', models.PositiveIntegerField(default=0, null=True)),
                ('mobile', models.PositiveIntegerField(default=0, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('Bio', models.TextField(max_length=2000, null=True)),
                ('github', models.URLField(default='', max_length=150, null=True)),
                ('facebook', models.URLField(default='', max_length=150, null=True)),
                ('website', models.URLField(default='', max_length=150, null=True)),
                ('twitter', models.URLField(default='', max_length=150, null=True)),
                ('instagram', models.URLField(default='', max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_tag', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('image', models.ImageField(default='image_blog.png', null=True, upload_to='media_blog')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_date', models.DateTimeField()),
                ('post_update', models.DateTimeField(null=True)),
                ('category', models.CharField(choices=[('Food blogs', 'Food blogs'), ('Travel blogs', 'Travel blogs'), ('Health and fitness blogs', 'Health and fitness blogs'), ('Lifestyle blogs', 'Lifestyle blogs'), ('Fashion and beauty blogs', 'Fashion and beauty blogs'), ('Photography blogs', 'Photography blogs'), ('Personal blogs', 'Personal blogs'), ('DIY craft blogs', 'DIY craft blogs'), ('Parenting blogs', 'Parenting blogs'), ('Music blogs', 'Music blogs'), ('Business blogs', 'Business blogs'), ('Art and design blogs', 'Art and design blogs'), ('Book and writing blogs', 'Book and writing blogs'), ('Personal finance blogs', 'Personal finance blogs'), ('Interior design blogs', 'Interior design blogs'), ('Sports blogs', 'Sports blogs'), ('News blogs', 'News blogs'), ('Movie blogs', 'Movie blogs'), ('Religion blogs', 'Religion blogs'), ('Political blogs', 'Political blogs'), ('others', 'others')], max_length=50, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile')),
            ],
        ),
    ]
